### ISSUE TITLE
Assertion error when bab-get_upper_bound argument is true

### ISSUE THREAD

**Issue by zhiluwang** [huanzhang12/alpha-beta-CROWN#3]
Hi,

When I tried to evaluate both the lower and upper bound of a NN by calling the bab() method in /complete_verifier/bab_verification_general.py, it has an assertion error in the `compute_bounds()` method in [auto_LiRPA/bound_general.py](https://github.com/huanzhang12/alpha-beta-CROWN/blob/11ef887edc3394f64caf64d9e5685882f506e2a4/auto_LiRPA/bound_general.py#L1080).

It seems that we cannot have `return_A == True` when calling `compute_bounds()` since `method == crown-optimized` (was set [here](https://github.com/huanzhang12/alpha-beta-CROWN/blob/11ef887edc3394f64caf64d9e5685882f506e2a4/complete_verifier/beta_CROWN_solver.py#L1601)). However, it seems that in this [build_the_model_with_refined_bounds()](https://github.com/huanzhang12/alpha-beta-CROWN/blob/11ef887edc3394f64caf64d9e5685882f506e2a4/complete_verifier/beta_CROWN_solver.py#L1554) method, `return_A` is set to `True` if we want to `get_upper_bound`.

Thanks for helping.

Zhilu

**Comment by huanzhang12** [comment]
@zhiluwang Thanks for reporting your issue to us! At this point, the `get_upper_bound` feature is still not ready to use, however we are working on completing this feature in the next release. If your aim is to get an upper bound of the objective of the robustness verification problem, one easy way to obtain an upper bound is by doing a PGD attack.

If you want to get an guaranteed upper bound for a function within a bounded input perturbation, you can do so by flipping the objective `g(x) = -f(x)`, so the lower bound reported by our tool is the actual upper bound you need. Let me know what is your exact use case so we can help you further.

**Comment by zhiluwang** [comment]
@huanzhang12 Thank you for the clarification. I am looking for using alpha-beta-crown for output range analysis of regression networks so I would like to evaluate an over-approximated upper bound. And my current solution is just like you mentioned, flipping the objective. I just thought that if lower and upper bounds can be derived together, it should be more efficient.

On the other hand, it seems that higher-level APIs are designed for classification networks. For output range analysis of regression networks, I currently call the `incomplete_verifier()` first and then call `bab()`. I set `y=None` and `arguments.Config["specification"]["norm"] = np.inf` to get a tight lower bound. Please correct me if there're better functions to use.

**Comment by huanzhang12** [comment]
@zhiluwang Yes, so far the API is indeed designed for classification network, and some minor changes are need to handle regression, although in principle they are the same the problem.

I am actually working on a more general interface at this time, but due to my limited availability I can't finish it very soon. The way you are currently doing should be correct. When you call `bab()`, I believe you will also need to give it a `target` (target class) and for regression, setting it to `0` should work.

**Comment by zhiluwang** [comment]
@huanzhang12  Got it. Thank you.
