### ISSUE TITLE
Bound backward error of BoundMaxPool layer

### ISSUE THREAD

**Issue by persistz** [huanzhang12/alpha-beta-CROWN#5]
I trained several adv trained models based on the origin github repo of Madry and Trades, even with the defination in `alpha-beta-CROWN/complete_verifier/model_defs.py`. 
When I use `robustness_verifier.py` to validate these models, an same error raised for all of them.

The error caused by the code `assert type(last_lA) == torch.Tensor or type(last_uA) == torch.Tensor` in `auto_LiRPA/operators/convolution.py` -> class `BoundMaxPool` -> function `bound_backward`.

When I check the type of `last_lA`, I found it is patches not tensor, so cannot pass the assert check.

I then checked the demos in `exp_configs`, I want to use a model and config provided by you to reproduce the error but I found unfortunately that it seems no model contains the MaxPool layer. If you need me to provide a model for reproducing this problem, I will be happy to do so.

**Comment by huanzhang12** [comment]
@persistz @Melcfrn Apologize for my late response. This is a known limitation of our current implementation, and so far we only support one maxpooling layer and a linear layer must be used after the maxpooling layer.

If your architecture does not meet this requirement, you can probably make it work by disabling Patch. If you network is small, it might work. You can do this by changing the `conv_mode` option to `matrix`, see https://github.com/huanzhang12/alpha-beta-CROWN/blob/8ed285c08becec7c0ac015731287f41b1a0f4861/docs/robustness_verifier_all_params.yaml#L4

We are working on a more general support for maxpooling layers, but this is not a top priority at this point so progress can be a bit slow. I will let you know when it is ready. Thank you.

**Comment by huanzhang12** [comment]
@persistz @Melcfrn The latest version of alpha-beta-CROWN and auto_LiRPA has better maxpool support (especially, `conv_mode: patches` to efficiently support Maxpool neurons), and you can try the latest version to see if it works for you.

**Comment by persistz** [comment]
Hi @huanzhang12 ,

Thanks for your updating and I will check it and close this issue soon.
