### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by Coder-Vishali** [huanzhang12/alpha-beta-CROWN#8]
When I try to execute the below command:
conda env create -f complete_verifier/environment.yml

I face this issue:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - xz==5.2.5=h7b6447c_0
  - x264==1!157.20191217=h7b6447c_0
  - mkl-service==2.3.0=py37he8ac12f_0
  - lcms2==2.12=h3be6417_0
  - _openmp_mutex==4.5=1_gnu
  - pluggy==0.13.1=py37h06a4308_0
  - giflib==5.2.1=h7b6447c_0
  - pytest==6.2.4=py37h06a4308_2
  - readline==8.1=h27cfd23_0
  - bottleneck==1.3.2=py37heb32a55_1
  - jpeg==9b=h024ee3a_2
  - libidn2==2.3.2=h7f8727e_0
  - numpy==1.19.2=py37h54aff64_0
  - ca-certificates==2021.10.26=h06a4308_2
  - ffmpeg==4.2.2=h20bf706_0
  - bzip2==1.0.8=h7b6447c_0
  - libprotobuf==3.17.2=h4ff587b_1
  - lame==3.100=h7b6447c_0
  - libwebp-base==1.2.0=h27cfd23_0
  - certifi==2021.10.8=py37h06a4308_0
  - lz4-c==1.9.3=h295c915_1
  - gnutls==3.6.15=he1e5248_0
  - sqlite==3.36.0=hc218d9a_0
  - libopus==1.3.1=h7b6447c_0
  - intel-openmp==2021.4.0=h06a4308_3561
  - openh264==2.1.0=hd408876_0
  - cudatoolkit==11.1.74=h6bb024c_0
  - nettle==3.7.3=hbbd107a_1
  - setuptools==58.0.4=py37h06a4308_0
  - gmp==6.2.1=h2531618_2
  - protobuf==3.17.2=py37h295c915_0
  - libunistring==0.9.10=h27cfd23_0
  - importlib-metadata==4.8.1=py37h06a4308_0
  - libuv==1.40.0=h7b6447c_0
  - pyyaml==6.0=py37h7f8727e_1
  - tk==8.6.11=h1ccaba5_0
  - freetype==2.11.0=h70c0345_0
  - ninja==1.10.2=hff7bd54_1
  - zlib==1.2.11=h7b6447c_3
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - libgomp==9.3.0=h5101ec6_17
  - ncurses==6.3=heee7806_1
  - zstd==1.4.9=haebb681_0
  - pip==21.0.1=py37h06a4308_0
  - pytorch==1.8.2=py3.7_cuda11.1_cudnn8.0.5_0
  - libffi==3.3=he6710b0_2
  - python==3.7.11=h12debd9_0
  - openssl==1.1.1l=h7f8727e_0
  - ld_impl_linux-64==2.35.1=h7274673_9
  - libgcc-ng==9.3.0=h5101ec6_17
  - pillow==8.4.0=py37h5aabda8_0
  - mkl_random==1.1.0=py37hd6b4f25_0
  - yaml==0.2.5=h7b6447c_0
  - libpng==1.6.37=hbc83047_0
  - libtiff==4.2.0=h85742a9_0
  - mkl_fft==1.3.0=py37h54f3939_0
  - pandas==1.3.4=py37h8c16a72_0
  - libtasn1==4.16.0=h27cfd23_0
  - libwebp==1.2.0=h89dd481_0
  - numpy-base==1.19.2=py37hfa32c7d_0
  - libvpx==1.7.0=h439df22_0
  - numexpr==2.7.3=py37hb2eb853_0

For your information, I am working on Windows OS.

**Comment by huanzhang12** [comment]
Windows is not supported directly, but you can try using WSL: https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by Coder-Vishali** [comment]
Thanks for the response

**Comment by Coder-Vishali** [comment]
Sure. I will try it out! Thanks for the response
